apiVersion: apps/v1
kind: Deploymentee
metadata:
  name: deployment-demo
  namespace: deploymentdemo
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deployment-demo
  template:
    metadata:
      labels:
        app: deployment-demo
    spec:
      containers:
      - name: deployment-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
