apiVersion: v1
kind: Service
metadata:
  name: deployment-demo
  namespace: deploymentdemo
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: deployment-demo
