
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rollout-canary-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "5"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: rollouts-demo
          servicePort: 80
