apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rollouts-demo-ingress
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    kubernetes.io/ingress.class: aws-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: iks-intuit-cidr-ingress-tcp-443, iks-intuit-app-alb-custom-ingress, iks-intuit-ibp-ingress-tcp-443
      
    external-dns.alpha.kubernetes.io/hostname: rollout-alb-test.ppd-west-2.iks.a.intuit.com
    alb.ingress.kubernetes.io/actions.rollouts-demo-stable: |
      {
        "Type":"forward",
        "ForwardConfig":{
          "TargetGroups":[
            {
                "Weight":0,
                "ServiceName":"rollouts-demo-canary",
                "ServicePort":"80"
            },
            {
                "Weight":100,
                "ServiceName":"rollouts-demo-stable",
                "ServicePort":"80"
            }
          ]
        }
      }
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: rollouts-demo-stable
              servicePort: 80
